# Nacos Console Port
nacos.console.port=18080
# Nacos Server Main Port
nacos.server.main.port=8848
# Database Type
spring.sql.init.platform=mysql
db.num=1
db.url.0=jdbc:mysql://jeecg-boot-mysql:3306/nacos?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
db.user=${MYSQL-USER:root}
db.password=${MYSQL-PWD:root}
# Nacos disables spring.datasource auto-configuration by default
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

# Metrics - Disabled
management.elastic.metrics.export.enabled=false
management.influx.metrics.export.enabled=false
# Nacos Config Push Max Retry Times
nacos.config.push.maxRetryTime=50
# Empty Service Auto Clean
nacos.naming.empty-service.auto-clean=true
nacos.naming.empty-service.clean.initial-delay-ms=50000
nacos.naming.empty-service.clean.period-time-ms=30000
# Nacos Context Path
nacos.server.contextPath=/nacos
# Access Log
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.max-days=30
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i
server.tomcat.basedir=file:.

# Include Error Message
spring.web.error.include-message=ALWAYS

# Nacos Console
nacos.console.contextPath=
nacos.console.remote.server.context-path=/nacos

# Security Config - Disable Auth
nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=false
nacos.core.auth.admin.enabled=false
nacos.core.auth.server.identity.key=nacos
nacos.core.auth.server.identity.value=nacos
nacos.core.auth.plugin.nacos.token.secret.key=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=

# Deployment Mode: merged
nacos.deployment.type=merged

# Fuzzy Match Config
nacos.config.fuzzy.watch.max.pattern.count=20
nacos.config.fuzzy.watch.max.pattern.match.config.count=500
nacos.naming.fuzzy.watch.max.pattern.count=20
nacos.naming.fuzzy.watch.max.pattern.match.service.count=500

# Disable AI Related Features
nacos.extension.ai.enabled=false
nacos.console.ad.enabled=false
