server:
   port: 8085
   servlet:
      context-path: /treesoft
spring:
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   profiles:
      active: dev
   redis:
      database: 5
      host: 172.18.26.81
      port: 6379
      timeout: 1000
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      maxActive: 20
      minIdle: 5
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      username: jeecg-boot
      password: ******
