server:
   port: 8085
spring:
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   profiles:
      active: dev
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      maxActive: 20
      minIdle: 5
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://172.18.26.81:3306/jeecg-boot?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      username: jeecg-boot
      password: 552200
