server:
    port: 8084
    url: http://msl1214.gnway.cc:8000

spring:
    redis:
        database: 5
        host: 127.0.0.1
        port: 6379
        timeout: 1000
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/jeecg-boot
        username: username
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    thymeleaf:
        cache: false
        mode: LEGACY HTML5
    mail:
        host: smtp.qq.com
        port: 587
        username: username
        password: password
        protocol: smtp
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
                      required: true
    servlet:
        multipart:
            max-file-size: 100MB
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

token:
    expire:
        link: 24
        ip: 10

